### PR TITLE
Optionally Disable Reverse Proxy

### PR DESCRIPTION
**Pull request by matthewdfuller**
Originally, the IAM proxy service acts as a reverse proxy for all requests to the AWS endpoint that are not destined for IAM metadata credentials. (/iam). This allows containers to request instance metadata, IP info, and other potentially sensitive information (especially user-data).

This PR adds a `DISABLE_UPSTREAM` environment variable which, when set to `true`, will respond to those requests with a 403 ACCESS DENIED. This should be used in any environments where containers should not have access to the instance's metadata.

### CODE REVIEW

**Comment by nahiluhmot** [comment]
Hey @matthewdfuller, thanks for contributing. The feature makes a lot of sense, but I'd change the implementation a bit. We typically store static configuration in [`struct app.Config`](https://github.com/swipely/iam-docker/blob/master/src/app/types.go#L18-L26), which is [initialized](https://github.com/swipely/iam-docker/blob/master/src/main.go#L46-L54) from [CLI arguments](https://github.com/swipely/iam-docker/blob/master/src/main.go#L16-L25) in `main.go`. I'll admit that using environment variables to control the configuration is more 12-factory and convenient, but let's keep things the way they are for now. I'd be interested in switching all configuration to environment variables in the future.

For now, could you please:

* Change the `$DISABLE_UPSTREAM` environment variable to a CLI argument
* Add a field to `reverseProxyAllowed` field (or something like that, I'm sure a better name exists) to `struct app.Config`
* Pass `reverseProxyAllowed` to [`http.NewIAMHandler`](https://github.com/swipely/iam-docker/blob/master/src/http/handler.go#L31)

**Comment by matthewdfuller** [comment]
@nahiluhmot - thanks for the feedback!

The above check failed (expectedly) because I am wondering how to pass the `disableUpstream` boolean from [here](https://github.com/swipely/iam-docker/pull/15/files#diff-f773a4aac47ee38b0e04b64fd8e7da02R32) into the `serveFastHTTP` function [here](https://github.com/swipely/iam-docker/pull/15/files#diff-f773a4aac47ee38b0e04b64fd8e7da02R42).

This is my first attempt at Go, so I apologize for the simple question :)

**Comment by matthewdfuller** [comment]
Hey @nahiluhmot - just a quick ping on this - what would be the best way to pass that param? Thanks!

**Comment by nahiluhmot** [comment]
Hey @matthewdfuller, sorry about the delayed response. 

[`httpHandler.serveFastHttp`](https://github.com/adobe-platform/iam-docker/blob/0abfe326382f1c158a017753e5fcf1729593c9ec/src/http/handler.go#L42) is a method defined on [`struct httpHandler`](https://github.com/adobe-platform/iam-docker/blob/0abfe326382f1c158a017753e5fcf1729593c9ec/src/http/handler.go#L143-L147). To use the `disableUpstream` boolean in `httpHandler.serveFastHttp`, I'd add a new field to `struct httpHandler` and pass the variable into the [`NewIAMHandler](https://github.com/adobe-platform/iam-docker/blob/0abfe326382f1c158a017753e5fcf1729593c9ec/src/http/handler.go#L32) function. Then you can use `struct httpHandler`'s `disableUpstream` member in `ServeFastHTTP`.

**Comment by matthewdfuller** [comment]
Np, thanks @nahiluhmot - everything should be as described now.

**Comment by nahiluhmot** [comment]
@matthewdfuller I think this looks good. Will merge and release tomorrow.

**Comment by nahiluhmot** [comment]
@matthewdfuller This was just [released](https://hub.docker.com/r/swipely/iam-docker/tags/) in `v1.2.0`. Thanks again!

**Pull request merged**
